<?php


// This file is part of the leeloolxpcert module for Moodle - http://moodle.org/


//


// Moodle is free software: you can redistribute it and/or modify


// it under the terms of the GNU General Public License as published by


// the Free Software Foundation, either version 3 of the License, or


// (at your option) any later version.


//


// Moodle is distributed in the hope that it will be useful,


// but WITHOUT ANY WARRANTY; without even the implied warranty of


// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the


// GNU General Public License for more details.


//


// You should have received a copy of the GNU General Public License


// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.





/**


 * Code fragment to define the version of the leeloolxpcert module


 *


 * @package    mod_leeloolxpcert


 * @copyright  2013 Mark Nelson <markn@moodle.com>


 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or late


 */





defined('MOODLE_INTERNAL') || die();





$plugin->component = 'mod_leeloolxpcert';





$plugin->release = '0.1.0';





$plugin->version = 2022091900;





$plugin->requires = 2018051700;





$plugin->maturity = MATURITY_ALPHA;
